name: Build
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@default
        with:
          version: 0.9.0
      - name: Build with zig cc
        run: zig cc main.c
